version: "2.1"

services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes_from:
      - app
    depends_on:
      - php

  php:
    build: ./php
    expose:
      - 9000
    links:
      - mysql
    volumes_from:
      - app

  app:
    image: nginx:latest
    volumes:
      - ./www/html:/var/www/html
    command: "true"


  mysql:
    image: mysql:latest
    volumes:
      - data:/var/lib/mysql
    # environment:
    #   MYSQL_DATABASE: project
    #   MYSQL_PASSWORD: project
    #   MYSQL_ROOT_PASSWORD: secret
    #   MYSQL_USER: project

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   ports:
  #     - 8080:80
  #   depends_on:
  #     - mysql
  #   environment:
  #     PMA_HOST: mysql

volumes:
  data:
